#!/usr/bin/env node

// ready from STDIN
// upper case all the text
// write to STDOUT


process.stdin.setEncoding('utf8');

process.stdin.on('readable', () => {
  const chunk = process.stdin.read();
  if (chunk !== null) {
    const reversedChunk = chunk.split('').reverse().join('')
    process.stdout.write(reversedChunk);
  }
});
